- .github/workflows/release.yaml
Related rlespinasse/github-slug-action#15
> ci: update to github-slug-action v1.1.1

- Dockerfile
> Installs perl into the container

- .github/workflows/release.yaml
> Updates github-slug-action version

- Dockerfile
> Pins yq version to 3.4.1

- Dockerfile
> Adds openvpn client to image

- Dockerfile
> Fixes kubectl cli download

- Dockerfile
Hi Team,
I have updated the Docker file to include aws cli . Please review and approve
> Updated Docker file with aws cli

- Dockerfile
> Fixes aws install for Alpine

- Dockerfile
> Adds yq4 to the image

- Dockerfile
Signed-off-by: Andrew Trice <amtrice@us.ibm.com>
> added azure cli

- Dockerfile
Reverts cloud-native-toolkit/image-cli-tools#25
> Revert "added azure cli"

- Dockerfile
> Adds gcompat

- README.md
> Updates readme with link to container registry and usage instructions

- Dockerfile
> Upgrades openshift cli to 4.10

- Dockerfile
> Adds openvpn to the image

- Dockerfile
> Removes unnecessary openvpn config

- Dockerfile
- README.md
> Adds terragrunt cli to the image

- .github/workflows/docker-build.yaml
- Dockerfile
- Adds workflow with support for amd64 and arm64 architectures
- Updates Dockerfile to support multiple architectures through TARGETPLATFORM arg
closes #47
> Adds workflow to build and push multi-arch image

- .github/workflows/docker-build.yaml
> Triggers docker build on published release

- .github/release-drafter-v1.1.yaml
- .github/workflows/docker-build.yaml
> Restructures tag template and adds tag prefix

- .github/workflows/docker-build.yaml
> Updates docker tag formatting from git tag

- .github/release-drafter-v1.1.yaml
- Dockerfile
> Updates yq4 to v4.25.2

- Dockerfile-alpine
- Dockerfile-fedora
> Updates base image to v1.2.0

- Dockerfile-alpine
- Dockerfile-fedora
> Updates base image to v1.2.1

- Dockerfile
- Dockerfile-alpine
- Dockerfile-fedora
> Updates base image to v1.2.2

- Dockerfile-alpine
- Dockerfile-fedora
appends a command to set group permissions to user after ibmcloud cli install
Signed-off-by: Tim Robinson <timroster@gmail.com>
> Fix permissions for IBM cloud cli plugin directory

- .github/workflows/docker-build.yaml
- Containerfile
- Containerfile-alpine
- Containerfile-fedora
- Dockerfile
> Updates base image to v1.4.0

- Containerfile-alpine
- Containerfile-fedora
> Updates base to v1.4.1

- .github/workflows/docker-build.yaml
- .github/workflows/update-base-image.yaml
- Containerfile-alpine
- Containerfile-fedora
- Adds workflow to create PR when cli-tools-core releases a new version
- Adds workflwo to notify downstream repos when new version released
> Updates base image to v1.4.2

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#1e0e312708b5f461cc72455599c9458e03dd6852
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.3

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#f58e3be37e2d2daf011dacb4f36fb00741702aa1
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.4

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#0829abc854bd6c148c4ebfb8e3f82bd455f236e2
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.5

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#163a5542c349377796b0f2b7047d0b970a28a02d
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.6

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#58dadd3e581a412dcae2f24d01e98e3b4466d0db
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.7

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#122c80fc563ed9dfae5bb1dabda91760a3b5bf8c
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.8

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#cd98eaac472303f299203df7b39b23d25e17d430
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.9

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#dc6e32baffb8a6c9fe57cb49bc7babf20d254b0d
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.10

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#e1dca86fcfcc5b0a82bc86fca19574ee65eae305
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.11

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#e3e47a035f09b2a99efe844b49c892558cb705c3
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.12

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#60f0988e5306be0ae2351d5848ae5d35ecd5fefa
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.13

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#b45bd08c729e36da596e86f7dcb7ea4efe927fa0
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.15

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#d23581bbf28551dd9174cfad47223d7fc4d8aec1
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.16

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#1ae05969cdbf2129b19aea9ccff753633a3b9bf3
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.17

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#55ee7b7179569c29cc81d1626b6dbfb577395c4b
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.18

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#7739a00d026f2800b8e3a60513fcc440d86101fc
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.19

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#9100e1417e00c65de0ebb16f8690cf85bf3af959
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.20

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#4419056e35dc7e021603afaa68eb0b78443fab26
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.5.0

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#628a0cb3bfc5e95a3800a2591e9f41877a1caf83
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.5.1

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#82e9c022b60e97589ea067f96d6dc16fb289fc67
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.6.0

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#04642906475c80c96c22a1f02b158bcc0e99318f
> Updates cloud-native-toolkit/image-cli-tools-core module to v1.6.1

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#587149809f923ee5de393c9130ec7f4ec7577fe5
> Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.2

- Containerfile-alpine
- Containerfile-fedora
cloud-native-toolkit/image-cli-tools-core}#23b35ec08b3601d944cc582c2ce7bf5a74f791ad
> Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.3
